# Minecraft / NeoForge
minecraft_version=1.21.1
neoforge_version=21.1.172

# Dependencies
voicechat_api_version=2.6.13
plasmovoice_api_version=2.1.17
plasmo_slib_version=1.7.5
lavaplayer_version=2.2.2
youtube_source_version=2be8e542d3f6f178e048dca565892684c2e40177-SNAPSHOT
# RU: Minecraft пиннит {strictly 4.5.13} | US: Minecraft pins {strictly 4.5.13}
httpclient_version=4.5.13

# Mod Properties
mod_base_version=1.2.0
mod_version_meta=1.21.1.neoforge
maven_group=dev.famjam.radiofm
mod_title=RadioFM
archives_base_name=RadioFM
mod_id=radiofm

# Compilation settings
org.gradle.jvmargs=-Xmx2G
